#!/bin/bash

ACCOUNT=${ACCOUNT-sam@gigster.com}
PROJECT_ID=$1

gcloud projects add-iam-policy-binding ${PROJECT_ID} \
  --member user:${ACCOUNT} \
  --role=roles/owner && \

yes | gcloud projects delete ${PROJECT_ID}
