cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'fzf'
brew 'go'
brew 'grc'
brew 'heroku'
brew 'htop'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'mongodb@3.0'
brew 'nativefier'
brew 'node'
brew 'nvm'
brew 'rabbitmq'
brew 'readline'
brew 'postgresql'
brew 'roundup'
brew 'sift'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask '3t-studio'
cask '1password'
# cask 'adium'
cask 'alfred2'
cask 'atom'
cask 'bartender'
cask 'catch'
# cask 'firefox'
# cask 'garmin-express'
cask 'github-desktop'
cask 'google-chrome'
cask 'caskroom/versions/google-chrome-canary'
cask 'insomnia'
cask 'iterm2'
cask 'java'
# cask 'handbrake'
# cask 'mapbox-studio'
# cask 'seashore'
cask 'magicprefs'
cask 'ngrok'
cask 'numi'
cask 'skype'
cask 'slack'
cask 'spectacle'
# cask 'steam'
cask 'transmission'
# cask 'tunnelbear'
casl 'virtualbox'
cask 'vlc'
