cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'elixir'
brew 'fzf'
brew 'github-release'
brew 'go'
brew 'grc'
brew 'htop'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'kubectl'
brew 'libgit2'
brew 'nativefier'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'readline'
brew 'roundup'
brew 'sift'
brew 'spaceman-diff'
brew 'spark'
brew 'terraform'

cask '1password'
cask 'alfred'
cask 'bartender'
cask 'catch'
cask 'dash'
cask 'docker'
cask 'github'
cask 'google-backup-and-sync'
cask 'google-cloud-sdk'
cask 'google-chrome'
cask 'insomnia'
cask 'iterm2'
cask 'middleclick'
cask 'numi'
cask 'phoenix'
cask 'slack'
cask 'transmission'
cask 'vlc'
