com.microsoft.VSCode js all
com.microsoft.VSCode ts all
com.microsoft.VSCode jsx all
com.microsoft.VSCode tsx all
com.microsoft.VSCode json all
com.microsoft.VSCode ex all
com.microsoft.VSCode exs all
com.microsoft.VSCode eex all
com.microsoft.VSCode tf all
com.microsoft.VSCode csv all
com.microsoft.VSCode yml all
com.microsoft.VSCode yaml all
com.microsoft.VSCode xml all
com.microsoft.VSCode c all
com.microsoft.VSCode cpp all
com.microsoft.VSCode h all
com.microsoft.VSCode php all